### ISSUE TITLE
Where can I download the .arrow files in the dataset folder？

### ISSUE THREAD

**Issue by WentaoTan** [nju-websoft/PairCoder#3]

**Comment by huanhuan6666** [comment]
Thank you for your interest in PairCoder!  

The `.arrow` files for the dataset folder are not included in the main repository due to their large size. However, you can download the complete dataset from the [[releases page](https://github.com/nju-websoft/PairCoder/releases/tag/v0.1.0)].  

### Steps to set up the dataset:
1. Go to the [[releases page](https://github.com/nju-websoft/PairCoder/releases/tag/v0.1.0)].
2. Download the `dataset.zip` file.
3. Unzip it and place the `dataset` folder in the root directory of the project.

This will ensure the dataset is properly configured for running the experiments.  

If you encounter any issues or have further questions, feel free to ask!

**Comment by WentaoTan** [comment]
Thank you very much!
